import type { FieldConfig } from "~/lib/types";

export const homeFieldConfig: FieldConfig[] = [
  {
    key: "text_nome",
    name: "text_nome",
    label: "Nome Completo",
    placeholder: "Digite seu nome completo",
    type: "text",
    font: 14,
    x: 323,
    y: 600,
    fontPdf: 12,
    xPdf: 120,
    yPdf: 131,
    required: true,
  },
  {
    key: "text_rg",
    name: "text_rg",
    label: "RG",
    placeholder: "Digite seu RG",
    type: "text",
    font: 12,
    x: 620,
    y: 430,
    fontPdf: 12,
    xPdf: 215,
    yPdf: 165,
    required: true,
  },
  {
    key: "text_cpf",
    name: "text_cpf",
    label: "CPF",
    placeholder: "Digite seu CPF",
    type: "text",
    font: 16,
    x: 440,
    y: 468,
    fontPdf: 16,
    xPdf: 100,
    yPdf: 190,
    required: true,
  },
  {
    key: "signature",
    name: "signature",
    label: "Assinatura",
    placeholder: "Clique para assinar",
    type: "signature",
    font: 0,
    x: 290,
    y: 530,
    fontPdf: 12,
    xPdf: 250,
    yPdf: 420,
    width: 240,
    height: 50,
    required: true,
  },
];
