import type { FieldConfig } from "~/lib/types";

export const homeFieldConfig: FieldConfig[] = [
  {
    key: "text_nome",
    name: "text_nome",
    label: "Nome Completo",
    placeholder: "Digite seu nome completo",
    type: "text",
    font: 14,
    x: 119,
    y: 133,
    fontPdf: 14,
    xPdf: 110,
    yPdf: 135,
    required: true,
  },
  {
    key: "text_rg",
    name: "text_rg",
    label: "RG",
    placeholder: "Digite seu RG",
    type: "text",
    font: 14,
    x: 261,
    y: 169,
    fontPdf: 14,
    xPdf: 215,
    yPdf: 165,
    required: true,
  },
  {
    key: "text_cpf",
    name: "text_cpf",
    label: "CPF",
    placeholder: "Digite seu CPF",
    type: "text",
    font: 16,
    x: 100,
    y: 206,
    fontPdf: 12,
    xPdf: 100,
    yPdf: 190,
    required: true,
  },
  {
    key: "text_universidade",
    name: "text_universidade",
    label: "Universidade",
    placeholder: "Digite o nome da universidade",
    type: "text",
    font: 12,
    x: 90,
    y: 245,
    fontPdf: 12,
    xPdf: 90,
    yPdf: 220,
    required: true,
  },
  {
    key: "text_semestre",
    name: "text_semestre",
    label: "Semestre",
    placeholder: "Digite o semestre atual",
    type: "text",
    font: 12,
    x: 268,
    y: 283,
    fontPdf: 12,
    xPdf: 215,
    yPdf: 247,
    required: true,
  },
  {
    key: "text_curso",
    name: "text_curso",
    label: "Curso",
    placeholder: "Digite o nome do curso",
    type: "text",
    font: 12,
    x: 90,
    y: 320,
    fontPdf: 12,
    xPdf: 90,
    yPdf: 275,
    required: true,
  },
  {
    key: "text_mes",
    name: "text_mes",
    label: "Mês",
    placeholder: "Digite o mês de referência",
    type: "text",
    font: 8,
    x: 357,
    y: 430,
    fontPdf: 8,
    xPdf: 287,
    yPdf: 357,
    required: true,
  },
  {
    key: "text_dias",
    name: "text_dias",
    label: "Dias",
    placeholder: "Digite o número de dias",
    type: "text",
    font: 12,
    x: 620,
    y: 430,
    fontPdf: 12,
    xPdf: 480,
    yPdf: 357,
    required: true,
  },
  {
    key: "text_cidade",
    name: "text_cidade",
    label: "Cidade",
    placeholder: "Digite a cidade da instituição",
    type: "text",
    font: 12,
    x: 440,
    y: 468,
    fontPdf: 12,
    xPdf: 340,
    yPdf: 385,
    required: true,
  },
  // Campo email sem coordenadas x,y (apenas dado)
  {
    key: "text_email",
    name: "text_email",
    label: "Email",
    placeholder: "Digite seu email",
    type: "email",
    font: 0, // 0 = não aparece na imagem
    x: 0, // 0 = não aparece na imagem
    y: 0, // 0 = não aparece na imagem
    fontPdf: 0, // 0 = não aparece no PDF
    xPdf: 0, // 0 = não aparece no PDF
    yPdf: 0, // 0 = não aparece no PDF
    required: true,
  },

  // Campo de assinatura
  {
    key: "signature",
    name: "signature",
    label: "Assinatura",
    placeholder: "Clique para assinar",
    type: "signature",
    font: 0,
    x: 290,
    y: 530,
    fontPdf: 12,
    xPdf: 250,
    yPdf: 420,
    width: 240,
    height: 50,
    required: true,
  },

  // Campo oculto para nome da assinatura (automático) - aparece na imagem e PDF
  {
    key: "text_repete",
    name: "text_repete",
    label: "Nome para Assinatura",
    placeholder: "Nome para assinatura no documento",
    type: "text",
    font: 12,
    x: 323,
    y: 600,
    fontPdf: 8,
    xPdf: 260,
    yPdf: 485,
    required: false,
    hidden: true, // Campo oculto no formulário - preenchido automaticamente
  },
];
