import type { FieldConfig } from "~/lib/types";
import { FieldFactories } from "~/lib/utils/field-config-factory";

export const homeFieldConfig: FieldConfig[] = [
  FieldFactories.text({
    key: "text_nome",
    name: "text_nome",
    label: "Nome Completo",
    placeholder: "Nome completo",
    font: 14,
    x: 119,
    y: 133,
    fontPdf: 14,
    xPdf: 110,
    yPdf: 135,
    required: true,
  }),

  FieldFactories.text({
    key: "text_rg",
    name: "text_rg",
    label: "RG",
    placeholder: "Seu RG",
    font: 14,
    x: 261,
    y: 169,
    fontPdf: 14,
    xPdf: 215,
    yPdf: 165,
    required: true,
  }),

  FieldFactories.text({
    key: "text_cpf",
    name: "text_cpf",
    label: "CPF",
    placeholder: "Seu CPF",
    font: 16,
    x: 100,
    y: 206,
    fontPdf: 13,
    xPdf: 100,
    yPdf: 190,
    required: true,
  }),

  FieldFactories.text({
    key: "text_universidade",
    name: "text_universidade",
    label: "Universidade",
    placeholder: "Sua universidade",
    font: 13,
    x: 90,
    y: 245,
    fontPdf: 13,
    xPdf: 90,
    yPdf: 220,
    required: true,
  }),

  FieldFactories.semester({
    key: "text_semestre",
    name: "text_semestre",
    label: "Semestre",
    placeholder: "Digite o número (ex: 1, 2, 10) - vira 1°, 2°, 10°",
    font: 12,
    x: 268,
    y: 283,
    fontPdf: 12,
    xPdf: 215,
    yPdf: 247,
    required: true,
  }),

  FieldFactories.text({
    key: "text_curso",
    name: "text_curso",
    label: "Curso",
    placeholder: "Nome do curso",
    font: 12,
    x: 90,
    y: 320,
    fontPdf: 12,
    xPdf: 90,
    yPdf: 275,
    required: true,
  }),

  FieldFactories.month({
    key: "text_mes",
    name: "text_mes",
    label: "Mês",
    placeholder: "Digite 1-12 (vira janeiro, fevereiro...) ou nome do mês",
    font: 9,
    x: 360,
    y: 430,
    fontPdf: 9,
    xPdf: 287,
    yPdf: 357,
    required: true,
  }),

  FieldFactories.text({
    key: "text_dias",
    name: "text_dias",
    label: "Dias",
    placeholder: "Número de dias",
    font: 12,
    x: 620,
    y: 430,
    fontPdf: 12,
    xPdf: 480,
    yPdf: 357,
    required: true,
  }),

  FieldFactories.text({
    key: "text_cidade",
    name: "text_cidade",
    label: "Cidade",
    placeholder: "Cidade da instituição",
    font: 12,
    x: 440,
    y: 468,
    fontPdf: 12,
    xPdf: 340,
    yPdf: 385,
    required: true,
  }),

  FieldFactories.hidden({
    key: "text_email",
    name: "text_email",
    label: "Email",
    placeholder: "Seu email",
    required: true,
  }),

  FieldFactories.signature({
    key: "signature",
    name: "signature",
    label: "Assinatura",
    placeholder: "Clique para assinar",
    font: 0,
    x: 290,
    y: 530,
    fontPdf: 12,
    xPdf: 200,
    yPdf: 420,
    width: 240,
    height: 50,
    required: true,
  }),

  FieldFactories.text({
    key: "text_repete",
    name: "text_repete",
    label: "Nome para Assinatura",
    placeholder: "Nome para assinatura no documento",
    font: 12,
    x: 323,
    y: 600,
    fontPdf: 8,
    xPdf: 260,
    yPdf: 485,
    required: false,
    hidden: true,
  }),
];
